server:
  port: 9297

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
#        bootstrap: true
        git:
          uri: https://github.com/Vinay9897/spring-config-server.git
          clone-on-start: true
          
#          https://github.com/igorkosandyak/demo-config-server.git