server:
  port: 9297

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/igorkosandyak/demo-config-server.git
          clone-on-start: true